install.packages('shiny')
install.packages('Hmisc')
install.packages('tmap')
install.packages('backports')
install.packages('dplyr')
install.packages('magick')
install.packages('expm')
install.packages('tidyverse')
install.packages('spdep')
install.packages('spdplyr')
install.packages('lubridate')
install.packages('extrafont')
install.packages('httr')
install.packages('rgdal')
install.packages('viridis')
install.packages('devtools')
install.packages('packcircles')
install.packages('hpackedbubble')
install.packages('ggiraph')
library(shiny)
library(magick)
library(ggplot2)
library(maps)
library(dplyr)
library(Hmisc)
library(tmap)
library(stringr)
library(ggmap)
library(ggthemes)
library(leaflet)
library(rgdal)
library(plotly)
library(ggmap)
library(expm)
library(extrafont)
library(httr)
library(lubridate)
library(magick)
library(rgdal)
library(spdep)
library(spdplyr)
library(tidyverse)
library(viridis)
library(devtools)
library(png)
library(purrr)


ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
  
)
server <- function(input,output){}
shinyApp(ui = ui, server = server)
